2019-09-24 13:20
CUDA_VISIBLE_DEVICES=0,1 python train.py --backbone xception \
--lr 0.007 \
--workers 2 \
--epochs 50 \
--batch-size 4 \
--gpu-ids 0,1 \
--checkname deeplab-xception \
--eval-interval 1 \
--dataset pascal

# 데이터 추가확보 (천안시)
# 2019-09-26 13:32
CUDA_VISIBLE_DEVICES=0,1 python train.py --backbone xception \
--lr 0.007 \
--workers 1 \
--epochs 50 \
--batch-size 6 \
--gpu-ids 0,1 \
--checkname deeplab-xception \
--eval-interval 1 \
--dataset pascal

# 24 epoch에서 멈춤, transfer learning 시작 
# 2019-09-30 09:53
CUDA_VISIBLE_DEVICES=0,1 python train.py --backbone xception \
--lr 0.007 \
--workers 1 \
--epochs 50 \
--start_epoch 25 \
--batch-size 6 \
--gpu-ids 0,1 \
--checkname deeplab-xception \
--eval-interval 1 \
--dataset pascal \
--resume /hdd/jaemin_ws/pytorch-deeplab-xception/run/pascal/deeplab-xception/model_best.pth.tar

# 데이터 픽셀에 대한 중복레이블 문제생김. 전처리 잘못해서 다시 시작.
# 2019-10-01 14:05
CUDA_VISIBLE_DEVICES=0,1 python train.py --backbone xception \
--lr 0.007 \
--workers 1 \
--epochs 50 \
--start_epoch 25 \
--batch-size 6 \
--gpu-ids 0,1 \
--checkname deeplab-xception \
--eval-interval 1 \
--dataset pascal
